# Generated by Django 5.1.6 on 2025-03-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(default='', max_length=20)),
                ('user_pass', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=12)),
                ('user_status', models.IntegerField(default='1')),
                ('role', models.CharField(default='team', max_length=100)),
            ],
        ),
    ]
