# Generated by Django 5.1.6 on 2025-03-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('Ground_name', models.CharField(default='', max_length=100)),
                ('ground_id', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('start_time', models.CharField(default='', max_length=100)),
                ('end_time', models.CharField(default='', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('Ground_name', models.CharField(default='', max_length=100)),
                ('ground_id', models.CharField(default='', max_length=100)),
                ('star', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('tid', models.CharField(max_length=100)),
                ('Tournament_name', models.CharField(default='', max_length=100)),
                ('ground_id', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
