# Generated by Django 5.1.6 on 2025-03-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournament_Booking',
            new_name='Match_Booking',
        ),
    ]
