# Generated by Django 5.1.6 on 2025-03-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_rename_tournament_booking_match_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_booking',
            old_name='Tournament_name',
            new_name='match_name',
        ),
        migrations.RenameField(
            model_name='match_booking',
            old_name='tid',
            new_name='mid',
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
