# Generated by Django 5.1.6 on 2025-03-20 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        ('Team', '0003_rename_tournament_name_match_booking_match_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='Ground_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rating',
            name='ground_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.registration'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('uid', 'ground_id')},
        ),
    ]
