# Generated by Django 5.1.6 on 2025-03-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100)),
                ('ground_name', models.CharField(max_length=100)),
                ('ground_location', models.CharField(default='', max_length=50)),
                ('ground_address', models.CharField(default='', max_length=50)),
                ('ground_desc', models.CharField(default='', max_length=1000)),
                ('ground_feature', models.CharField(default='', max_length=50)),
                ('ground_rate', models.CharField(default='', max_length=50)),
                ('ground_img', models.ImageField(default='', upload_to='images')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host_Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=100)),
                ('tournament_name', models.CharField(max_length=100)),
                ('tournament_date', models.CharField(default='', max_length=20)),
                ('tournament_desc', models.CharField(default='', max_length=750)),
                ('tournament_rate', models.CharField(default='', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
