# Generated by Django 5.1.6 on 2025-03-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groundregistration',
            name='ground_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
