# Generated by Django 5.1.6 on 2025-03-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0002_groundregistration_ground_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Host_Tournament',
            new_name='Host_Match',
        ),
        migrations.RenameField(
            model_name='host_match',
            old_name='tournament_date',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='host_match',
            old_name='tournament_desc',
            new_name='match_desc',
        ),
        migrations.RenameField(
            model_name='host_match',
            old_name='tournament_name',
            new_name='match_name',
        ),
        migrations.RenameField(
            model_name='host_match',
            old_name='tournament_rate',
            new_name='match_rate',
        ),
    ]
