# Generated by Django 5.1.6 on 2025-03-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizer', '0004_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
